// Generated by CoffeeScript 1.10.0
(function() {
  var UserException;

  UserException = (function() {
    function UserException(msg) {
      this.message = msg;
      this.name = "User Error";
    }

    UserException.prototype.toString = function() {
      return this.name + ": \"" + this.name + "\"";
    };

    return UserException;

  })();

  exports.UserException = UserException;

}).call(this);

//# sourceMappingURL=exception.js.map
