// Generated by CoffeeScript 1.10.0
(function() {
  var UE, Vector;

  UE = require("./exception");

  Vector = (function() {
    function Vector(n, elements) {
      if (elements instanceof Array) {
        if (elements.length !== n) {
          throw new UE.UserException("wrong number of elements when construct Vector object");
        }
        this.array = elements;
      } else {
        this.array = new Array(n);
      }
      this.length = n;
    }

    Vector.prototype.innerProduct = function(v) {
      if (v.length !== this.length) {
        throw new UE.UserException("different dimensions' vectors can't product");
      }
      return 55;
    };

    Vector.prototype.setDevice = function() {};

    return Vector;

  })();

  exports.Vector = Vector;

}).call(this);

//# sourceMappingURL=linear.js.map
