// Generated by CoffeeScript 1.10.0
(function() {
  var JC, a, array, f32a, f32aa, i, j, k, len, num;

  JC = require("./jc/build/Debug/jc.node");

  JC.cudaDeviceInit();

  f32aa = (function() {
    var j, results;
    results = [];
    for (num = j = 0; j < 100; num = ++j) {
      results.push(new Float32Array(num));
    }
    return results;
  })();

  array = (function() {
    var j, len, results;
    results = [];
    for (j = 0, len = f32aa.length; j < len; j++) {
      f32a = f32aa[j];
      results.push(new JC.DeviceFloat32Array(f32a));
    }
    return results;
  })();

  for (i = j = 0, len = array.length; j < len; i = ++j) {
    a = array[i];
    array[i] = null;
  }

  for (i = k = 0; k < 100; i = ++k) {
    array.push(i);
  }

  console.log(array.length);

  JC.cudaDeviceReset();

}).call(this);

//# sourceMappingURL=objectTest.js.map
